deploy-infra

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,20 +20,32 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v4
 
+    - name: Debug repo structure (DO NOT REMOVE YET)
+      run: |
+        echo "PWD:"
+        pwd
+        echo "ROOT FILES:"
+        ls -la
+        echo "TERRAFORM FOLDER:"
+        ls -la terraform || echo "terraform folder NOT FOUND"
+
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2
 
     - name: Terraform Init
       run: |
-        terraform init \
+        terraform -chdir=terraform init \
           -backend-config="bucket=${TF_STATE_BUCKET_NAME}" \
           -backend-config="region=${AWS_REGION}"
 
+    - name: Terraform Validate
+      run: terraform -chdir=terraform validate
+
     - name: Terraform Plan
       run: |
-        terraform plan \
+        terraform -chdir=terraform plan \
           -var="region=${AWS_REGION}" \
           -var="key_name=deployer"
 
     - name: Terraform Apply
-      run: terraform apply -auto-approve
+      run: terraform -chdir=terraform apply -auto-approve
